apiVersion: v1
kind: Pod
metadata:
  labels:
    test: busybox-pod
  name: busybox-pod
spec:
  schedulerName: BRMSScheduler
  containers:
  - name: iscsi-pv-busybox
    image: busybox
    command: ["sleep", "60000"]

